from tkinter import *
def findLargest():
    list1=[]
    list1.append(int(contenten1.get()))
    list1.append(int(contenten2.get()))
    list1.append(int(contenten3.get()))
    contentLargest.set(max(list1))

window=Tk()
window.title("Largest Number")
Label(window,text="First Number:").grid(row=0,column=0,pady=5,sticky=E)
contenten1=StringVar()
entnum1=Entry(window,width=8,textvariable=contenten1)
entnum1.grid(row=0,column=1,sticky=W)
Label(window,text="Second Number:").grid(row=1,column=0,pady=5,sticky=E)
contenten2=StringVar()
entnum2=Entry(window,width=8,textvariable=contenten2)
entnum2.grid(row=1,column=1,sticky=W)
Label(window,text="Third Number:").grid(row=2,column=0,pady=5,sticky=E)
contenten3=StringVar()
entnum3=Entry(window,width=8,textvariable=contenten3)
entnum3.grid(row=2,column=1,sticky=W)
btnFind=Button(window,text="Find the largest number",command=findLargest)
btnFind.grid(row=3,column=0,columnspan=2,padx=75)
Label(window,text="Largest number:").grid(row=4,column=0,sticky=E)
contentLargest=StringVar()
entLargest=Entry(window,state="readonly",width=8,textvariable=contentLargest)
entLargest.grid(row=4,column=1,pady=5,sticky=W)
window.mainloop()